#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const assert = require('assert')
const { exec, execSync } = require('child_process');
const { logger } = require('log-instance');
const { WaveFile } = require('wavefile');

// avoid Tensorflow include via ../index
const Chart = require('../src/chart');
const ResonatorBank = require('../src/resonator-bank');
const Signal = require('../src/signal');
const YinPitch = require('../src/yin-pitch');

const APP_DIR = path.dirname(__dirname);
const TEST_DATA_DIR = path.join(APP_DIR, 'test/data');
const EVAM_ME_SUTTAM_WAV = path.join(TEST_DATA_DIR, 'evam-me-suttam.wav');
const AN9_20_4_3_WAV = path.join(TEST_DATA_DIR, 'an9.20_4.3.wav');
const argv = process.argv;
const script = argv[1].split('/').pop();
const SOUND_END = path.join(APP_DIR, 'static/training-end.mp3');
const SOUND_SUCCESS = path.join(APP_DIR, 'static/training-success.mp3');
const SOUND_FAILURE = path.join(APP_DIR, 'static/training-failure.mp3');
const SOUND_ADJUST = path.join(APP_DIR, 'static/training-adjust.mp3');

function help() {
    console.log(`
NAME
        formants - audio formant analyser

SYNOPSIS
        formants [OPTIONS] 
        formants -si INPUT_WAV 

DESCRIPTION
        Speech formant analyser detects F0, F1, F2 for given WAV signal.

    -cl, --chart-lines N
        Number of lines used to chart worst signal mismatch (15)

    -?, --help
        Print help

    -ad, --acf-diff
        Maximum ACF difference threshold (0.1);

    -fb, --frequency-band FMIN FMAX
        Minimum and maximium speech frequenciesy recognized (85 300).
        Male speech is in the 85-150Hz band.  Female speech is in the 160-255Hz band.
        Child speech is at 300 Hz.

    -fs, --frame-size
        Input is broken up into frames.

    -ha, --harmonic-amplitude
        Minimum harmonic amplitude to be recognized as a harmonic (1)

    -ho, --harmonic-output WAV_FILE
        Harmonic resonator WAV signal

    -ll, --log-level
        Logging level: warn, error, [info], debug

    -mp, --min-power
        Minimum signal power for pitch recognition (128)

    -rc, --resonator-count COUNT
        Count of resonators in harmonic helmholz resonator bank (20)

    -rr, --resonator-r R1,RN
        Feedback coefficient tweening interval for resonator bank (0.995,0.98)

    -si, --signal-in WAV_FILE
        Input signal 

    -sk, --skew NSAMPLES
        Advance output by given number of samples (10)

    -tr, --tween-resonator
        Interpolate resonator changes (false)

    -wi, --window
        Auto-correlation window size (551)
`);
    process.exit(0);
}

function playSound(sound) {
  let cmd = `ffplay -nodisp -autoexit -loglevel error -stats ${sound}`;
  execSync(cmd, {
    cwd: APP_DIR,
  });
}

function die(e) {
  playSound(SOUND_FAILURE);
  process.exit(-1);
}

var cmdCfg = {};

var nargs = argv.length;
if (nargs < 3) {
    help();
}
for (var i = 2; i < nargs; i++) {
  var arg = argv[i];
  let requiredArg = ()=>{
    let nextArg = argv[++i];
    if (nextArg == null) {
      die(logger.error('E_REQUIRED', `Expected additional information for: ${arg}`));
    }
    return nextArg;
  }
  let requiredNumber = ()=>{
    let n = Number(requiredArg());
    if (isNaN(n)) {
      die(logger.error(`[E_NUMBER] "${argv[i-1]}" option requires a number:${argv[i]}`));
    }
    return n;
  }
  if (i<2) { continue; }
  if (arg === '-?' || arg === '--help') {
    help();
    cmdCfg.signalExpected = requiredArg();
  } else if (arg === '-ad' || arg === '--acf-diff') {
    cmdCfg.diffMax = requiredNumber();
  } else if (arg === '-fb' || arg === '--frequency-band') {
    cmdCfg.fMin = requiredNumber();
    cmdCfg.fMax = requiredNumber();
  } else if (arg === '-fs' || arg === '--frame-size') {
    cmdCfg.frameSize = requiredNumber();
  } else if (arg === '-ha' || arg === '--harmonic-amplitude') {
    cmdCfg.minAmplitude = requiredNumber();
  } else if (arg === '-ho' || arg === '--harmonic-out') {
    cmdCfg.harmonicOut = requiredArg();
  } else if (arg === '-mp' || arg === '--min-power') {
    cmdCfg.minPower = requiredNumber();
  } else if (arg === '-si' || arg === '--signal-in') {
    cmdCfg.signalIn = requiredArg();
  } else if (arg === '-ll' || arg === '--log-level') {
    cmdCfg.logLevel = logger.logLevel = requiredArg();
  } else if (arg === '-rc' || arg === '--resonator-count') {
    cmdCfg.resonatorCount = requiredNumber();
  } else if (arg === '-rr' || arg === '--resonator-r') {
    cmdCfg.resonatorR = requiredArg().split(',').map(v=>Number(v));
  } else if (arg === '-sk' || arg === '--skew') {
    cmdCfg.skew = requiredNumber();
  } else if (arg === '-tr' || arg === '--tweenResonator') {
    cmdCfg.tweenResonator = true;
  } else if (arg === '-wi' || arg === '--window') {
    cmdCfg.window = requiredNumber();
  } else {
    die(logger.error('E_UNKNOWN_OPTION', `Unknown option: ${argv[i]}`));
  }
}

async function wavSignal(fpath) {
  assert(fpath, `Expected signal file path: ${fpath}`);
  let buf = await fs.promises.readFile(fpath);
  let wf = new WaveFile(buf);
  //let wavSig = new Signal(wf.getSamples(false, Int16Array));
  let wavSig = Signal.fromWav(buf);
  let { sampleRate } = wavSig;
  let stats = wavSig.stats();
  logger.debug(`wavSignal`, fpath, stats);
  logger.info(`wavSignal() ${fpath} =>`, `max:`, stats.max, `count:`, stats.count,
    `sampleRate:`, sampleRate);

  return wavSig;
}

async function configuration(cfg=cmdCfg) {
  let { 
    harmonicOut,
    signalIn, 
  } = cfg;

  assert(fs.existsSync(signalIn), `[E_SIGNAL_IN] file not found:${signalIn}`);

  return Object.assign({}, {
    chartLines: 15,
    diffMax: 0.1,
    fMin: 85,
    fMax: 300,
    harmonicOut,
    frameSize: 192,
    logLevel: 'info',
    minAmplitude: 1,
    minPower: 1,
    resonatorCount: 20,
    resonatorR: 0.98,
    skew: 10,
    signalIn,
    tweenResonator: false,
    verbose: false,
    window: 551,

  }, cfg, {
  });
}

async function writeSignal(fpath, signal) {
  if (fpath.endsWith('.wav')) {
    let wav = signal.toWav();
    try {
      await fs.promises.writeFile(fpath, wav);
      logger.info(`writing signal: ${fpath} length: ${wav.length}`);
    } catch(e) {
      die(logger.error(`Could not write: ${fpath}`, e.message));
    }
  } else {
    die(logger.error('E_FILE_UNSUPPORTED', `Unsupported file type: ${fpath}`));
  }
}

function inputsOfFrames(frames, inputSize) {
  let frameSize = frames[0].length;
  let wavFrames = Math.ceil(inputSize / frameSize);
  let iEnd = frames.length - 1;
  let inputs = frames.map((f,i) => {
    let inputRow = [];
    for (let j=i; j < i+wavFrames; j++) {
      let fj = frames[j] || new Float32Array(frameSize);
      inputRow = inputRow.concat([...fj]);
    }
    return inputRow;
  });
  return inputs;
}

(async function() {
  let cfg = await configuration(cmdCfg);
  let msStart = Date.now();
  let { 
    chartLines,
    diffMax,
    fMin,
    fMax,
    frameSize,
    harmonicOut,
    minAmplitude,
    minPower,
    resonatorCount,
    resonatorR,
    signalIn, 
    skew,
    tweenResonator,
    verbose,
    window,

  } = cfg;
  let resBank = new ResonatorBank({
    r:resonatorR, 
    length: resonatorCount, 
    frameSize,
    tween: tweenResonator,
  });
  let dataOut = [];
  logger.info(script, argv.slice(2).join(' '));
  verbose && logger.info(`command options parsed as`, cfg);

  let sigIn = await wavSignal(signalIn);
  let { data:sigData, sampleRate } = sigIn;
  let yp = new YinPitch({
    sampleRate, diffMax, fMin, fMax, window, minAmplitude, minPower,
  });
  let nSamples = Math.ceil(yp.minSamples / frameSize) * frameSize;
  logger.info({nSamples, sigData:sigData.length});

  let power = [];
  let h0 = [];
  for (let i = 0; i < sigData.length; i += frameSize) {
    let samples = sigData.subarray(i, i+nSamples);
    if (samples.length === nSamples) {
      let harmonics = yp.harmonics(samples);
      dataOut = dataOut.concat(resBank.resonate(harmonics));
      if (harmonics.length) {
        let {frequency:f0, amplitude:a0} = harmonics[0];
        let { pitch } = yp.pitch(samples);
        verbose && logger.info(`${f0.toFixed(1)}Hz`, harmonics
          .sort((a,b)=>b.amplitude-a.amplitude)
          .map(h=>`h${h.order}:${h.amplitude.toFixed(0)}`)
          .join(', '));
        h0.push(harmonics[0].frequency);
      } else {
        verbose && logger.info(`frame:${i} t:${(i/sampleRate).toFixed(3)}`);
      }
    } else {
      logger.debug(`discarding partial samples[${i}]:${samples.length}`);
    }
  }
  let chart = new Chart({lines:chartLines});
  verbose && chart.plot({ title:`1:h0, 2:power`, data:[h0], xInterval:4 });

  let elapsed = ((Date.now()-msStart)/60000).toFixed(1);

  if (harmonicOut) {
    let dataIn = sigIn.data;
    if (skew) {
      let tail = resBank.resonate([], {nSamples:skew + dataIn.length - dataOut.length});
      dataOut = [...dataOut.slice(skew), ...tail];
    }
    await writeSignal(harmonicOut, new Signal(dataOut));
    let mse = Signal.rmsErr(dataIn, dataOut);
    logger.info(`harmonicOut => ${harmonicOut}`,
      `dataIn:${dataIn.length}`,
      `dataOut:${dataOut.length}`,
      `mse:${mse}`);
    await playSound(harmonicOut);
    chart.plot({data:[dataIn, dataOut], xInterval:4});
  }

  process.exit(0);
})();
