#!/bin/bash

if [ "$1" ]; then LAYERS=$1;    shift; else LAYERS=3;       fi
if [ "$1" ]; then CODESIZE=$1;  shift; else CODESIZE=12;    fi
if [ "$1" ]; then FRAMESIZE=$1; shift; else FRAMESIZE=192;  fi
if [ "$1" ]; then NOISE=$1;     shift; else NOISE=512;      fi
if [ "$1" ]; then EPOCHS=$1;    shift; else EPOCHS=100;     fi
if [ "$1" ]; then WAVFRAMES=$1; shift; else WAVFRAMES=2;    fi
if [ "$1" ]; then EPOCH1=$1;    shift; else EPOCH1=0;       fi
if [ "$1" ]; then UNITS=$1;     shift; else UNITS=9;        fi

SUFFIX=w${WAVFRAMES}l${LAYERS}c${CODESIZE}f${FRAMESIZE}
echo "LAYERS=$LAYERS UNITS=$UNITS CODESIZE=$CODESIZE" \
  "SUFFIX=$SUFFIX NOISE=$NOISE EPOCHS=$EPOCHS FRAMESIZE=$FRAMESIZE"
MODEL=local/$SUFFIX/ko-pana-vado
EXPECTED=test/data/ko-pana-vado.wav
SIGNAL=local/m3l1u9c192/ko-pana-vado.wav
#AUDIO=evam-me-suttam
AUDIO=ko-pana-vado
ATTEMPTS=3
BATCHSIZE=256

mkdir -p $MODEL

echo $MODEL "$0"
scripts/wav2-coder \
  -mp $MODEL \
  -el $LAYERS \
  -eu 0.$UNITS \
  -fs $FRAMESIZE \
  -cs $CODESIZE \
  -si $SIGNAL \
  -se $EXPECTED \
  -tr $ATTEMPTS \
  -ie $EPOCH1 \
  -ep $EPOCHS \
  -bs $BATCHSIZE \
  -nk $NOISE \
  -wf $WAVFRAMES \
  -sv test/data/$AUDIO.wav \
  -so local/$SUFFIX/$AUDIO.wav 2>&1 | tee -a local/$SUFFIX/train.log 
RC=${PIPESTATUS[0]}
echo LAYERS=$LAYERS UNITS=$UNITS CODESIZE=$CODESIZE SUFFIX=$SUFFIX NOISE=$NOISE EPOCHS=$EPOCHS
echo "TRAINING $MODEL => $RC"
