#!/bin/bash

if [ "$1" ]; then LAYERS=$1;   shift; else LAYERS=3;    fi
if [ "$1" ]; then UNITS=$1;    shift; else UNITS=9;     fi
if [ "$1" ]; then CODESIZE=$1; shift; else CODESIZE=12; fi
if [ "$1" ]; then NOISE=$1;    shift; else NOISE=1;     fi
if [ "$1" ]; then EPOCHS=$1;   shift; else EPOCHS=100;  fi

SUFFIX=m3l${LAYERS}u${UNITS}c${CODESIZE}
echo LAYERS=$LAYERS UNITS=$UNITS CODESIZE=$CODESIZE SUFFIX=$SUFFIX NOISE=$NOISE EPOCHS=$EPOCHS
MODEL=local/$SUFFIX/an9.20_4.3
SCALE=test/data/an9.20_4.3-mdct3-stats.json
SIGNAL=test/data/an9.20_4.3.wav
#AUDIO=evam-me-suttam
AUDIO=ko-pana-vado
ATTEMPTS=3
BATCHSIZE=256

mkdir -p $MODEL

echo $MODEL "$0"
scripts/mdct3-coder \
  -mp $MODEL \
  -scm $SCALE \
  -el $LAYERS \
  -eu 0.$UNITS \
  -cs $CODESIZE \
  -si $SIGNAL \
  -tr $ATTEMPTS \
  -ep $EPOCHS \
  -bs $BATCHSIZE \
  -nk $NOISE \
  -sv test/data/$AUDIO.wav \
  -so local/$SUFFIX/$AUDIO.wav 2>&1 | tee -a local/$SUFFIX/train.log 
RC=${PIPESTATUS[0]}
echo "TRAINING $MODEL => $RC"
